redesign/component/menu
gofynd/nitrozen-react pull request #27
Opened 2023-01-30 01:52 UTC by sujoydev99

2023-01-30 05:11 UTC, ShahRohan27 commented
@sujoydev99 please revert the package.json changes

2023-01-30 05:49 UTC, sujoydev99 commented
changes reverted

2023-01-30 05:49 UTC, sujoydev99 commented
@ShahRohan27 changes reverted

2023-01-31 06:14 UTC, ShahRohan27 requested changes

2023-01-31 06:14 UTC, ShahRohan27 commented on src/components/Menu/Menu.stories.tsx
> +        <svg fill="none" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
Refer checkbox story on how to pass Icons.

2023-01-31 06:14 UTC, ShahRohan27 commented on src/components/Menu/Menu.test.tsx
> +    //open
Remove if not required

2023-01-31 06:14 UTC, ShahRohan27 commented on src/base/variable.scss
> +$MenuItemFontSize: 16px;
Use $BaseFontSize + 6 instead of add a new variable

2023-02-01 00:10 UTC, sujoydev99 commented
Issue : -
Now : Redesigned menu component, captured all use cases.

# Menu Component
- simple
<img width="216" alt="image" src="https://user-images.githubusercontent.com/37466838/215912220-3f161d3a-cbe6-4a05-af17-ce99144b2426.png">


- only labels
<img width="165" alt="Screenshot 2023-02-01 at 4 46 01 AM" src="https://user-images.githubusercontent.com/37466838/215912056-d828e8a0-1cd7-48da-b2f2-09a5ff80bffa.png">

- with links
<img width="216" alt="Screenshot 2023-02-01 at 5 29 12 AM" src="https://user-images.githubusercontent.com/37466838/215912118-ef7bff0e-c1f8-4513-b39d-3b189697a994.png">


- mixed
<img width="216" alt="Screenshot 2023-02-01 at 5 30 03 AM" src="https://user-images.githubusercontent.com/37466838/215912099-6e17542a-6b3f-4c2a-81e7-90330f4334c7.png">


- no icons
<img width="165" alt="Screenshot 2023-02-01 at 4 45 50 AM" src="https://user-images.githubusercontent.com/37466838/215912399-991d822f-4b2c-494e-8822-30138db9c740.png">


- anchored to any element
<img width="165" alt="Screenshot 2023-02-01 at 4 46 13 AM" src="https://user-images.githubusercontent.com/37466838/215912260-74753617-8648-49c2-b718-1db076ee5171.png"> 
<img width="216" alt="image" src="https://user-images.githubusercontent.com/37466838/215912320-c79b0116-72ba-4b70-886c-ec084cc82bb6.png">


## tests
<img width="472" alt="Screenshot 2023-02-01 at 5 38 53 AM" src="https://user-images.githubusercontent.com/37466838/215912963-1c593cb3-164e-4a11-a1ba-e9b7c54a9291.png">

2023-02-01 12:24 UTC, merged