fix(table checkbox): fixed checkbox click issue on triggering onRowClick
gofynd/nitrozen-react pull request #82
Opened 2023-04-20 07:24 UTC by subhomoy-roy-choudhury

1. Stopped onclick event on table checkbox when we apply onRowClick on the whole table row

2023-04-20 07:32 UTC, d-suman1 requested changes

2023-04-20 07:32 UTC, d-suman1 commented on src/components/Table/Table.test.tsx
> +  test("Table checkbox clickable but row is not clicked", async () => {
Please update the test description to something more descriptive. e.g. "on clicking checkbox event should not be propagated to rowClick".

2023-04-20 10:08 UTC, d-suman1 approved these changes
LGTM

2023-04-21 05:25 UTC, subhomoy-roy-choudhury commented on src/components/Table/Table.tsx
> +                <div className="n-table-checkbox-wrapper">
changes done

2023-04-24 07:22 UTC, merged